version: '3.4'

services:
  asb-test:
    container_name: asb_node
    image: asb-test
    restart: always
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 5000
    links: 
      - mongo
  mongo:
    container_name: asb_mongo
    image: mongo
    ports:
      - '27017:27017'